const $=s=>document.querySelector(s);
const colors=[['#d5e4f65c','#718dac'],['#e1d9f966','#9182b9'],['#d7ede96b','#739e92'],['#f5e5cf6b','#b49970']];
const initialMap=[{"id":"root","title":"Mon stage chez Sofinco","note":"Crédit Agricole Personal Finance & Mobility\nRoubaix · du 11 janvier au 19 février\nResponsables commerciaux et Business Tech","x":565,"y":245,"parent":null,"c":0},{"id":"interets","title":"Mes centres d’intérêt","note":"• Sport : surtout le football\n• Sports automobiles : surtout la F1\n• Cinéma, films et séries","x":190,"y":45,"parent":"root","c":0},{"id":"projets","title":"Mes projets et objectifs","note":"2e année de BTS SAM\n\nPistes à personnaliser :\n• Découvrir les équipes commerciales et Business Tech\n• Développer mes compétences d’appui aux responsables\n• Préciser mon projet professionnel","x":950,"y":45,"parent":"root","c":1},{"id":"scolaire","title":"Mes exigences scolaires","note":"• Effectuer une veille si elle n’est pas déjà réalisée\n• Identifier des situations en contexte international\n• Remplir les fiches E4\n• Conserver les preuves du stage\n\nSujet de veille et contexte international à préciser","x":190,"y":385,"parent":"root","c":2},{"id":"personnel","title":"Mes contraintes personnelles","note":"Je me déplace en transports en commun.\n\nÀ prévoir :\n• Organiser le trajet jusqu’à Roubaix\n• Vérifier les correspondances et les horaires\n• Prévoir une marge pour arriver à l’heure","x":950,"y":385,"parent":"root","c":3}];
const formerMap=[{"id":"root","title":"Mon stage idéal","note":"Le point de départ de ma réflexion","x":565,"y":250,"parent":null,"c":0},{"id":"interets","title":"Mes centres d’intérêt","note":"Ce qui me plaît, ce qui me motive…","x":190,"y":80,"parent":"root","c":0},{"id":"projets","title":"Mes projets","note":"Mes envies scolaires et professionnelles…","x":950,"y":80,"parent":"root","c":1},{"id":"scolaire","title":"Mes contraintes scolaires","note":"Veille, contexte international, attendus…","x":190,"y":410,"parent":"root","c":2},{"id":"personnel","title":"Mes contraintes personnelles","note":"Transport, distance, disponibilités…","x":950,"y":410,"parent":"root","c":3}];
let nodes=initialMap.map(n=>({...n}));
let zoom=1,tx=0,ty=0,editing=null,selected='root',drag=null,toastTimer;

const STORAGE_KEY='nebule.mindmap.v1';
let storageReady=false;
const saveStatus=document.createElement('span');
saveStatus.id='save-status';
saveStatus.setAttribute('role','status');
saveStatus.style.cssText='font-size:12px;color:#6d798a';
document.querySelector('footer').replaceChildren(saveStatus);
function status(message,failed=false){saveStatus.textContent=message;saveStatus.style.color=failed?'#a34854':'#6d798a'}
function validMap(data){
 if(!data||data.version!==1||!Array.isArray(data.nodes)||!data.nodes.length)return false;
 const ids=new Set();
 for(const n of data.nodes){
  if(!n||typeof n.id!=='string'||ids.has(n.id)||typeof n.title!=='string'||!n.title.trim()||n.title.length>70||typeof n.note!=='string'||n.note.length>700||!Number.isFinite(n.x)||!Number.isFinite(n.y)||!Number.isInteger(n.c)||n.c<0||n.c>=colors.length)return false;
  ids.add(n.id);
 }
 const root=data.nodes.find(n=>n.id==='root');
 if(!root||root.parent!==null)return false;
 const byId=new Map(data.nodes.map(n=>[n.id,n]));
 for(const n of data.nodes){const seen=new Set();let p=n;while(p.id!=='root'){if(seen.has(p.id)||!byId.has(p.parent))return false;seen.add(p.id);p=byId.get(p.parent)}}
 return true;
}
function persist(){
 if(!storageReady)return;
 try{localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,nodes}));status('Enregistré dans ce navigateur');return true}
 catch{status('Sauvegarde impossible : le stockage du navigateur est indisponible.',true);return false}
}
function restore(){
 try{const raw=localStorage.getItem(STORAGE_KEY);if(raw!==null){const data=JSON.parse(raw);if(!validMap(data))throw Error('Invalid saved map');nodes=data.nodes.map(n=>{const before=formerMap.find(p=>p.id===n.id),after=initialMap.find(p=>p.id===n.id);if(before&&after&&n.title===before.title&&n.note===before.note)return {...after,x:n.x,y:n.y,parent:n.parent};return n});status('Carte restaurée · sauvegarde automatique')}else status('Sauvegarde automatique dans ce navigateur')}
 catch{status('Sauvegarde illisible ou inaccessible. Les données existantes sont conservées.',true)}
}
restore();

const icons={root:'✳',interets:'♡',projets:'↗',scolaire:'▤',personnel:'⌁'};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2400)}
function transform(){$('#world').style.transform=`translate(${tx}px,${ty}px) scale(${zoom})`;$('#scale').textContent=Math.round(zoom*100)+' %'}
function fit(){const w=$('#viewport').clientWidth,h=$('#viewport').clientHeight;zoom=Math.min(1,w/1270,h/620);if(w<700)zoom=Math.max(.6,zoom);tx=(w-1400*zoom)/2;ty=(h-650*zoom)/2;transform()}
function lines(){const svg=$('#links');svg.replaceChildren();for(const n of nodes){if(!n.parent)continue;const p=nodes.find(p=>p.id===n.parent);if(!p)continue;const right=n.x>p.x;const pw=p.id==='root'?270:252;const x1=p.x+(right?pw:0),y1=p.y+70,x2=n.x+(right?0:252),y2=n.y+68;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M ${x1} ${y1} C ${(x1+x2)/2} ${y1}, ${(x1+x2)/2} ${y2}, ${x2} ${y2}`);path.style.stroke=colors[n.c][1];svg.append(path)}}
function render(){const container=$('#nodes');container.replaceChildren();for(const n of nodes){const el=document.createElement('button');el.type='button';el.className='node'+(n.id==='root'?' root':'');el.dataset.id=n.id;el.style.cssText=`left:${n.x}px;top:${n.y}px;--tint:${colors[n.c][0]};--ink:${colors[n.c][1]}`;el.setAttribute('aria-label',`Modifier ${n.title}`);const icon=document.createElement('span');icon.className='node-icon';icon.textContent=icons[n.id]||'✧';const title=document.createElement('h3');title.textContent=n.title;const note=document.createElement('p');note.textContent=n.note;const edit=document.createElement('span');edit.className='edit';edit.textContent='↗';el.append(icon,title,note,edit);el.addEventListener('click',e=>{if(!el.wasDragged)openEditor(n.id);el.wasDragged=false});el.addEventListener('pointerdown',e=>{if(e.button!==0)return;selected=n.id;drag={id:n.id,x:e.clientX,y:e.clientY,ox:n.x,oy:n.y,moved:false,el};el.setPointerCapture(e.pointerId)});el.addEventListener('pointermove',e=>{if(!drag||drag.id!==n.id)return;const dx=(e.clientX-drag.x)/zoom,dy=(e.clientY-drag.y)/zoom;if(Math.abs(dx)+Math.abs(dy)>5)drag.moved=true;if(!drag.moved)return;n.x=drag.ox+dx;n.y=drag.oy+dy;el.style.left=n.x+'px';el.style.top=n.y+'px';lines()});const end=()=>{if(drag){el.wasDragged=drag.moved;if(drag.moved)persist();drag=null}};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);container.append(el)}$('#count').textContent=nodes.length+' cellules';lines();persist()}
function descendants(id){const found=new Set([id]);let change=true;while(change){change=false;for(const n of nodes)if(found.has(n.parent)&&!found.has(n.id)){found.add(n.id);change=true}}return found}
function openEditor(id=null){editing=id;const n=nodes.find(n=>n.id===id);$('#dialog-title').textContent=n?'Modifier l’idée':'Une nouvelle idée';$('#title').value=n?.title||'';$('#note').value=n?.note||'';$('#delete').hidden=!n||id==='root';const invalid=id?descendants(id):new Set();$('#parent').replaceChildren();for(const p of nodes){if(invalid.has(p.id))continue;const o=document.createElement('option');o.value=p.id;o.textContent=p.title;$('#parent').append(o)}$('#parent').disabled=id==='root';$('#parent').value=n?.parent||selected;$('#editor').showModal();$('#title').focus()}
function addIdea(title,note,parent){if(typeof title!=='string'||!title.trim()||title.length>70||typeof note!=='string'||note.length>700)throw Error('Titre ou texte invalide.');const p=nodes.find(n=>n.id===parent);if(!p)throw Error('Cellule parente introuvable.');const id='idea-'+crypto.randomUUID();nodes.push({id,title:title.trim(),note,parent,c:p.id==='root'?nodes.length%4:p.c,x:p.x+300,y:p.y+150+nodes.filter(n=>n.parent===parent).length*35});render();return{id,title:title.trim()}}
$('#form').addEventListener('submit',e=>{e.preventDefault();const title=$('#title').value.trim();if(!title){$('#title').setCustomValidity('Écris un titre pour cette idée.');$('#title').reportValidity();return}if(editing){const n=nodes.find(n=>n.id===editing);n.title=title;n.note=$('#note').value;if(n.id!=='root')n.parent=$('#parent').value;render()}else addIdea(title,$('#note').value,$('#parent').value);$('#editor').close();toast('Ton idée a trouvé sa place')});$('#title').addEventListener('input',()=>$('#title').setCustomValidity(''));$('#close').onclick=()=>$('#editor').close();$('#add').onclick=()=>openEditor();$('#delete').onclick=()=>{const n=nodes.find(n=>n.id===editing);for(const child of nodes)if(child.parent===n.id)child.parent=n.parent;nodes=nodes.filter(x=>x.id!==editing);selected='root';render();$('#editor').close();toast('Cellule supprimée · les idées reliées sont conservées')};
function changeZoom(delta){const next=Math.max(.3,Math.min(1.7,zoom+delta)),cx=$('#viewport').clientWidth/2,cy=$('#viewport').clientHeight/2;tx=cx-(cx-tx)*next/zoom;ty=cy-(cy-ty)*next/zoom;zoom=next;transform()}$('#plus').onclick=()=>changeZoom(.1);$('#minus').onclick=()=>changeZoom(-.1);$('#fit').onclick=fit;
let pan=null;$('#viewport').addEventListener('pointerdown',e=>{if(e.target.closest('.node'))return;pan={x:e.clientX,y:e.clientY,tx,ty};$('#viewport').setPointerCapture(e.pointerId)});$('#viewport').addEventListener('pointermove',e=>{if(!pan)return;tx=pan.tx+e.clientX-pan.x;ty=pan.ty+e.clientY-pan.y;transform()});for(const evt of ['pointerup','pointercancel'])$('#viewport').addEventListener(evt,()=>pan=null);window.addEventListener('resize',fit);render();fit();storageReady=true;
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'add_mindmap_idea',description:'Ajoute une cellule à la carte mentale affichée.',inputSchema:{type:'object',properties:{title:{type:'string',maxLength:70},note:{type:'string',maxLength:700},parent:{type:'string'}},required:['title','note','parent'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({title,note,parent})=>addIdea(title,note,parent)})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'read_mindmap',description:'Lit les cellules et les liens de la carte mentale.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({nodes:nodes.map(n=>({...n}))})})).catch(()=>{})}catch{}}
